version: '{build}'
image: Visual Studio 2017
configuration: Release
before_build:
- ps: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: /.*\.nupkg/
  name: NuGet Package
deploy:
  provider: NuGet
  api_key:
    secure: tH3DhfLidY7oekSNx32ehYWvgbKUBovka+AXhZb7tFIiYvhLTHYvX8sLQkMNVRLp
  skip_symbols: true
  artifact: /.*\.nupkg/